---
- name: install languages
  homebrew: name={{item}} state=latest
  with_items:
    - cabal-install
    - elixir
    - erlang
    - go
    - groovy
    - lua
    - node
    - python
    - ruby
    - rust
    - scala

- name: install package managers
  homebrew: name={{item}} state=latest
  with_items:
    - gradle
    - leiningen
    - maven
    - npm

- name: setup .zsh directory
  file: path=~/.zsh state=directory recurse=yes

- name: install language profile configurations
  copy: src={{item.src}} dest={{item.dest}}
  with_items:
    - { src: 'bundler.zsh', dest: '~/.zsh/bundler.zsh' }
    - { src: 'gem.zsh', dest: '~/.zsh/gem.zsh' }
    - { src: 'groovy.zsh', dest: '~/.zsh/groovy.zsh' }
    - { src: 'gemrc', dest: '~/.gemrc' }
    - { src: 'irbrc', dest: '~/.irbrc' }
