- name: install shell configurations
  copy: src={{item.src}} dest={{item.dest}} backup=yes
  with_items:
    - { src: "zshrc", dest: "~/.zshrc" }

- name: Install packages
  homebrew:
    name:
      - awscli
      - autojump
      - jq
      - mas
      - scala
      - sbt
      - git
      - wget

- name: Install cask packages
  homebrew_cask:
    name:
      - alfred
      - atom
      - iterm2
      - firefox
      - docker
      - google-chrome
      - macvim
      - visual-studio-code
      - intellij-idea-ce
      - plex
      - spotify
    install_options: force

- name: install iterm2  configurations
  copy: src={{item.src}} dest={{item.dest}}
  with_items:
    - { src: "com.googlecode.iterm2.plist", dest: "~/Library/Preferences/com.googlecode.iterm2.plist" }